# CoxPH brief, Appendix A: pprof_py's R reference results (pprof_py/r_reference/results, made with
# R 4.3.3, survival 3.5-8 and glmnet 4.1-8 on Linux) regenerated by pprof_py's own scripts with the
# installed R packages, and compared file by file. The regenerated results stay in the scratch
# directory, where 03 and 04 read them.
# Found on 2026-10-07 (R 4.4.0, survival 3.8-12, glmnet 5.1, Windows): the 87 survival-based files
# are identical except one, within 1e-15; the 25 glmnet files changed (coefficient paths by up to
# 2.5e-5, the cross-validation results by far more).
# Run from the repository root: Rscript dev/design/coxph-facts/02_r_reference_drift.R <output file>
args <- commandArgs(trailingOnly = TRUE)
pprof_py <- normalizePath(Sys.getenv("PPROF_PY", "../../pprof_py"), winslash = "/", mustWork = TRUE)
scratch <- Sys.getenv("COXPH_FACTS_SCRATCH")
if (!nzchar(scratch)) stop("Set COXPH_FACTS_SCRATCH (see README.md)")
reference <- file.path(pprof_py, "pprof_py", "r_reference")
work <- file.path(scratch, "r_reference")
unlink(work, recursive = TRUE)
dir.create(file.path(work, "data"), recursive = TRUE)
invisible(file.copy(list.files(file.path(reference, "data"), full.names = TRUE), file.path(work, "data")))
scripts <- c("run_all.R", "run_penalized.R", "run_phase4_competing_risks.R", "run_phase4_robust.R",
             "run_phase4_timedep.R", "run_selection.R")
invisible(file.copy(file.path(reference, scripts), work))
rscript <- file.path(R.home("bin"), "Rscript")
owd <- setwd(work)
status <- vapply(scripts, function(s) system2(rscript, c(s, "."), stdout = FALSE, stderr = FALSE), 0L)
setwd(owd)

old_dir <- file.path(reference, "results")
new_dir <- file.path(work, "results")
files <- sort(list.files(old_dir, pattern = "\\.csv$"))
compare <- function(f) {
  o <- read.csv(file.path(old_dir, f))
  n <- read.csv(file.path(new_dir, f))
  if (!identical(dim(o), dim(n))) {
    return(data.frame(file = f, status = "dimensions differ", max_abs = NA_real_, max_rel = NA_real_, column = ""))
  }
  num <- names(o)[vapply(o, is.numeric, TRUE) & vapply(n, is.numeric, TRUE)]
  labels_same <- all(vapply(setdiff(names(o), num),
                            function(cc) identical(as.character(o[[cc]]), as.character(n[[cc]])), TRUE))
  d <- abs(as.matrix(o[num]) - as.matrix(n[num]))
  a <- abs(as.matrix(o[num]))
  rel <- ifelse(a > 1e-8, d / a, 0)
  worst <- if (length(d) && max(d, na.rm = TRUE) > 0) num[which(d == max(d, na.rm = TRUE), arr.ind = TRUE)[1, 2]] else ""
  data.frame(file = f,
             status = if (!labels_same) "labels differ" else if (all(d == 0, na.rm = TRUE)) "identical" else "differs",
             max_abs = if (length(d)) max(d, na.rm = TRUE) else 0,
             max_rel = if (length(rel)) max(rel, na.rm = TRUE) else 0,
             column = worst)
}
res <- do.call(rbind, lapply(files, compare))
res$engine <- ifelse(startsWith(res$file, "penalized_"), "glmnet", "survival")
res <- res[order(res$engine, -res$max_abs, res$file), ]
fmt <- function(x) ifelse(is.na(x), "NA", formatC(x, format = "e", digits = 2))
summary_line <- function(engine) {
  r <- res[res$engine == engine, ]
  sprintf("%s-based files: %d; identical %d; differing %d (largest absolute difference %s)",
          engine, nrow(r), sum(r$status == "identical"), sum(r$status != "identical"),
          fmt(max(r$max_abs, na.rm = TRUE)))
}
lines <- c(
  sprintf("Regenerated with %s, survival %s, glmnet %s (%s); compared with pprof_py's committed results.",
          R.version.string, packageVersion("survival"), packageVersion("glmnet"), R.version$platform),
  sprintf("Scripts run: %s", paste(sprintf("%s (exit %d)", names(status), status), collapse = ", ")),
  summary_line("survival"), summary_line("glmnet"), "",
  "| File | Engine | Status | Max abs diff | Max rel diff | Column |",
  "|---|---|---|---|---|---|",
  sprintf("| %s | %s | %s | %s | %s | %s |", res$file, res$engine, res$status, fmt(res$max_abs),
          fmt(res$max_rel), res$column))
writeLines(lines, args[1])
