# Phase 5 planning: D-27 (integer provider IDs and parm) in the methods Phase 5 replaces.
args <- commandArgs(trailingOnly = TRUE)
.libPaths(c("dev/reference/lib", .Library))
Sys.setlocale("LC_COLLATE", "C")
Sys.setenv(OMP_THREAD_LIMIT = "1")
suppressPackageStartupMessages(library(pprof))
lines <- character()
say <- function(...) lines <<- c(lines, paste0(...))
quiet <- function(expr) suppressMessages(suppressWarnings(expr))
try_call <- function(label, expr) {
  res <- tryCatch({ v <- quiet(expr); sprintf("value (%d rows)", NROW(if (is.data.frame(v)) v else v[[1]])) },
                  error = function(e) paste("error:", conditionMessage(e)))
  say(sprintf("%s -> %s", label, res))
}
data(ExampleDataLinear)
data(ExampleDataBinary)
lin <- data.frame(Y = ExampleDataLinear$Y, ProvID = as.integer(ExampleDataLinear$ProvID), ExampleDataLinear$Z)
bin <- data.frame(Y = ExampleDataBinary$Y, ProvID = as.integer(ExampleDataBinary$ProvID), ExampleDataBinary$Z)
z <- paste0("z", 1:5)
lfe <- quiet(linear_fe(data = lin, Y.char = "Y", Z.char = z, ProvID.char = "ProvID"))
say(sprintf("linear_fe data_include ProvID class: %s", class(lfe$data_include$ProvID)))
try_call("test.linear_fe(parm = 1:3)", test(lfe, parm = 1:3))
try_call("SM_output.linear_fe(parm = 1:3)", SM_output(lfe, parm = 1:3))
try_call("confint.linear_fe(parm = 1:3)", confint(lfe, parm = 1:3))
try_call("test.linear_fe(parm = c(1, 2, 3))", test(lfe, parm = c(1, 2, 3)))
lre <- quiet(linear_re(data = lin, Y.char = "Y", Z.char = z, ProvID.char = "ProvID"))
say(sprintf("linear_re data_include ProvID class: %s", class(lre$data_include$ProvID)))
try_call("test.linear_re(parm = 1:3)", test(lre, parm = 1:3))
lcre <- quiet(linear_cre(data = lin, Y.char = "Y", ProvID.char = "ProvID", wb.char = "z1", other.char = z[-1]))
say(sprintf("linear_cre data_include ProvID class: %s", class(lcre$data_include$ProvID)))
try_call("test.linear_cre(parm = 1:3)", test(lcre, parm = 1:3))
kcre <- quiet(logis_cre(data = bin, Y.char = "Y", ProvID.char = "ProvID", wb.char = "z1", other.char = z[-1]))
say(sprintf("logis_cre data_include ProvID class: %s", class(kcre$data_include$ProvID)))
try_call("test.logis_cre(parm = 1:3)", test(kcre, parm = 1:3))
try_call("SM_output.logis_cre(parm = 1:3)", SM_output(kcre, parm = 1:3, threads = 1))
try_call("confint.logis_cre(parm = 1:3)", confint(kcre, parm = 1:3))
writeLines(lines, args[1])
