# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

computeDirectExp <- function(est, Z_beta, threads) {
    .Call(`_pprof_computeDirectExp`, est, Z_beta, threads)
}

cpp_logistic_fe_serbin <- function(response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, backtrack, stop_rule, threads) {
    .Call(`_pprof_cpp_logistic_fe_serbin`, response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, backtrack, stop_rule, threads)
}

cpp_logistic_fe_ban <- function(response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, backtrack, stop_rule, threads) {
    .Call(`_pprof_cpp_logistic_fe_ban`, response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, backtrack, stop_rule, threads)
}

cpp_logistic_firth <- function(response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, threads) {
    .Call(`_pprof_cpp_logistic_firth`, response, design, provider_sizes, gamma, beta, max_iter, tol, effect_bound, threads)
}

cpp_logistic_firth_log_determinant <- function(diagonal, schur) {
    .Call(`_pprof_cpp_logistic_firth_log_determinant`, diagonal, schur)
}

cpp_logistic_variance <- function(design, provider_sizes, gamma, beta) {
    .Call(`_pprof_cpp_logistic_variance`, design, provider_sizes, gamma, beta)
}

cpp_logistic_score_standard <- function(response, design, provider_sizes, gamma, beta, gamma_null, providers, threads) {
    .Call(`_pprof_cpp_logistic_score_standard`, response, design, provider_sizes, gamma, beta, gamma_null, providers, threads)
}

cpp_logistic_direct_expected <- function(effects, linear_predictor, threads) {
    .Call(`_pprof_cpp_logistic_direct_expected`, effects, linear_predictor, threads)
}

